version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/birthdayCampaign
      - EMAIL_USER=pritam.bhalerao9284@gmail.com
      - EMAIL_PASS=ticz eees rxct bnji
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm run build && node dist/main.js"]

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
